# Generated by Django 2.1.7 on 2019-02-16 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.PositiveIntegerField()),
                ('account_no', models.BigIntegerField(unique=True)),
                ('card_no', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.PositiveIntegerField()),
                ('amount', models.BigIntegerField()),
                ('account_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmeans.Customer', to_field='account_no')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmeans.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kmeans.TransactionType'),
        ),
    ]
