# Generated by Django 2.1.7 on 2019-02-16 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction Summary',
                'verbose_name_plural': 'Transactions Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('kmeans.transaction',),
        ),
    ]
