# Generated by Django 2.1.7 on 2019-02-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmeans', '0002_transactionsummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Channel', 'verbose_name_plural': 'Channels'},
        ),
    ]
